//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//------------------------------------------------------------------------------
using System;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using recipesApp.EntityClasses;

namespace recipesApp
{
	/// <summary>Class which represents the DataContext for the project / group 'RecipesApp'</summary>
	public partial class RecipesAppDataContext : DbContext
	{
		partial void OnModelCreatingComplete();

		/// <summary>Constructor which accepts an already setup DbContextOptions instance</summary>
		/// <param name="options">The DbContextOptions object to use</param>
		public RecipesAppDataContext(DbContextOptions<RecipesAppDataContext> options) : base(options) {}
		
		/// <summary>Empty constructor which relies on OnConfiguring being overriden</summary>
		public RecipesAppDataContext() : base() {}
		
		/// <inheritdoc/>
		public override int SaveChanges(bool acceptAllChangesOnSuccess)
		{
			CheckReadonlyEntities();
			return base.SaveChanges(acceptAllChangesOnSuccess);
		}

		/// <inheritdoc/>
		public override Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = new CancellationToken())
		{
			CheckReadonlyEntities();
			return base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken);
		}
		
		/// <inheritdoc/>
		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			new RecipesAppModelBuilder().BuildModel(modelBuilder);
			OnModelCreatingComplete();
		}

		private void CheckReadonlyEntities()
		{
			var namesOfChangedReadOnlyEntities = this.ChangeTracker.Entries().Where(e => e.Metadata.IsReadOnly() && e.State != EntityState.Unchanged).Select(e => e.Metadata.Name).Distinct().ToList();
			if(namesOfChangedReadOnlyEntities.Any())
			{
				throw new InvalidOperationException($"Attempted to save the following read-only entitie(s): {string.Join(",", namesOfChangedReadOnlyEntities)}");
			}
		}

		/// <summary>Gets an object query for the entity set 'Category', containing entity type 'Category'</summary>
		public DbSet<Category> Categories { get; set; } 
		/// <summary>Gets an object query for the entity set 'Ingredient', containing entity type 'Ingredient'</summary>
		public DbSet<Ingredient> Ingredients { get; set; } 
		/// <summary>Gets an object query for the entity set 'Instruction', containing entity type 'Instruction'</summary>
		public DbSet<Instruction> Instructions { get; set; } 
		/// <summary>Gets an object query for the entity set 'Recipe', containing entity type 'Recipe'</summary>
		public DbSet<Recipe> Recipes { get; set; } 
		/// <summary>Gets an object query for the entity set 'RecipeCategory', containing entity type 'RecipeCategory'</summary>
		public DbSet<RecipeCategory> RecipeCategories { get; set; } 
		/// <summary>Gets an object query for the entity set 'User', containing entity type 'User'</summary>
		public DbSet<User> Users { get; set; } 
		/// <summary>Gets an object query for the entity set 'VersionInfo', containing entity type 'VersionInfo'</summary>
		public DbSet<VersionInfo> VersionInfos { get; set; } 
	}
}
