//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace View.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Recipe'.</summary>
	[Serializable]
	[DataContract]
	public partial class RecipeDetailsView
	{
		/// <summary>Gets or sets the Ingredients field. </summary>
		[DataMember]
		public List<RecipeDetailsViewTypes.Ingredient> Ingredients { get; set; }
		/// <summary>Gets or sets the Instructions field. </summary>
		[DataMember]
		public List<RecipeDetailsViewTypes.Instruction> Instructions { get; set; }
		/// <summary>Gets or sets the Title field. Derived from Entity Model Field 'Recipe.Title'</summary>
		[DataMember]
		public System.String Title { get; set; }
	}

	namespace RecipeDetailsViewTypes
	{
		/// <summary> DTO class which is derived from the entity 'Ingredient (Ingredients)'.</summary>
		[Serializable]
		[DataContract]
		public partial class Ingredient
		{
			/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'Ingredient.Name'</summary>
			[DataMember]
			public System.String Name { get; set; }
		}

		/// <summary> DTO class which is derived from the entity 'Instruction (Instructions)'.</summary>
		[Serializable]
		[DataContract]
		public partial class Instruction
		{
			/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'Instruction.Name'</summary>
			[DataMember]
			public System.String Name { get; set; }
		}
	}

}




