//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace View.Persistence
{
	/// <summary>Static class for (extension) methods for fetching and projecting instances of View.DtoClasses.RecipeMenuView from the entity model.</summary>
	public static partial class RecipeMenuViewPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<recipesApp.EntityClasses.Recipe, View.DtoClasses.RecipeMenuView>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<recipesApp.EntityClasses.Recipe, View.DtoClasses.RecipeMenuView> _compiledProjector = CreateProjectionFunc().Compile();
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static RecipeMenuViewPersistence() { }
	
		/// <summary>Extension method which produces a projection to View.DtoClasses.RecipeMenuView which instances are projected from the 
		/// results of the specified baseQuery, which returns recipesApp.EntityClasses.Recipe instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve View.DtoClasses.RecipeMenuView instances</returns>
		public static IQueryable<View.DtoClasses.RecipeMenuView> ProjectToRecipeMenuView(this IQueryable<recipesApp.EntityClasses.Recipe> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}

		/// <summary>Extension method which produces a projection to View.DtoClasses.RecipeMenuView which instances are projected from the
		/// recipesApp.EntityClasses.Recipe entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>recipesApp.EntityClasses.Recipe instance created from the specified entity instance</returns>
		public static View.DtoClasses.RecipeMenuView ProjectToRecipeMenuView(this recipesApp.EntityClasses.Recipe entity)
		{
			return _compiledProjector(entity);
		}
		
		private static System.Linq.Expressions.Expression<Func<recipesApp.EntityClasses.Recipe, View.DtoClasses.RecipeMenuView>> CreateProjectionFunc()
		{
			return p__0 => new View.DtoClasses.RecipeMenuView()
			{
				Id = p__0.Id,
				Ingredients = p__0.Ingredients.Select(p__1 => new View.DtoClasses.RecipeMenuViewTypes.Ingredient()
				{
					Name = p__1.Name,
				}).ToList(),
				Instructions = p__0.Instructions.Select(p__1 => new View.DtoClasses.RecipeMenuViewTypes.Instruction()
				{
					Name = p__1.Name,
				}).ToList(),
				RecipeCategories = p__0.RecipeCategories.Select(p__1 => new View.DtoClasses.RecipeMenuViewTypes.RecipeCategory()
				{
					Category = new View.DtoClasses.RecipeMenuViewTypes.RecipeCategoryTypes.Category()
					{
						Name = p__1.Category.Name,
					},
				}).ToList(),
				Title = p__0.Title,
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_RecipeMenuView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
		}
	}
}


