//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace recipesApp.EntityClasses
{
	/// <summary>Class which represents the entity 'Category'.</summary>
	public partial class Category : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _id = default(System.Int32);

		/// <summary>Initializes a new instance of the <see cref="Category"/> class.</summary>
		public Category() : base()
		{
			this.RecipeCategories = new List<RecipeCategory>();
			this.Name = string.Empty;
			OnCreated();
		}

		/// <summary>Gets the Id field. </summary>
		public System.Int32 Id => _id;
		/// <summary>Gets or sets the IsActive field. </summary>
		public System.Boolean IsActive { get; set; }
		/// <summary>Gets or sets the Name field. </summary>
		public System.String Name { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'RecipeCategory.Category - Category.RecipeCategories (m:1)'</summary>
		public virtual List<RecipeCategory> RecipeCategories { get; set; }
	}
}
