//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace recipesApp.EntityClasses
{
	/// <summary>Class which represents the entity 'Instruction'.</summary>
	public partial class Instruction : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _id = default(System.Int32);

		/// <summary>Initializes a new instance of the <see cref="Instruction"/> class.</summary>
		public Instruction() : base()
		{
			this.Name = string.Empty;
			OnCreated();
		}

		/// <summary>Gets the Id field. </summary>
		public System.Int32 Id => _id;
		/// <summary>Gets or sets the IsActive field. </summary>
		public System.Boolean IsActive { get; set; }
		/// <summary>Gets or sets the Name field. </summary>
		public System.String Name { get; set; }
		/// <summary>Gets or sets the RecipeId field. </summary>
		public System.Int32 RecipeId { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'Instruction.Recipe - Recipe.Instructions (m:1)'</summary>
		public virtual Recipe Recipe { get; set; } = null!;
	}
}
