//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace recipesApp.EntityClasses
{
	/// <summary>Class which represents the entity 'RecipeCategory'.</summary>
	public partial class RecipeCategory : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();
		private System.Int32 _id = default(System.Int32);

		/// <summary>Initializes a new instance of the <see cref="RecipeCategory"/> class.</summary>
		public RecipeCategory() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the CategoryId field. </summary>
		public System.Int64 CategoryId { get; set; }
		/// <summary>Gets the Id field. </summary>
		public System.Int32 Id => _id;
		/// <summary>Gets or sets the RecipeId field. </summary>
		public System.Int64 RecipeId { get; set; }
		/// <summary>Represents the navigator which is mapped onto the association 'RecipeCategory.Category - Category.RecipeCategories (m:1)'</summary>
		public virtual Category Category { get; set; } = null!;
		/// <summary>Represents the navigator which is mapped onto the association 'RecipeCategory.Recipe - Recipe.RecipeCategories (m:1)'</summary>
		public virtual Recipe Recipe { get; set; } = null!;
	}
}
