//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System;
using System.Collections.Generic;

namespace recipesApp.EntityClasses
{
	/// <summary>Class which represents the entity 'VersionInfo'.</summary>
	public partial class VersionInfo : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="VersionInfo"/> class.</summary>
		public VersionInfo() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the AppliedOn field. </summary>
		public Nullable<System.DateTime> AppliedOn { get; set; }
		/// <summary>Gets or sets the Description field. </summary>
		public System.String? Description { get; set; }
		/// <summary>Gets or sets the Version field. </summary>
		public System.Int64 Version { get; set; }
	}
}
