//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace recipeDatabase.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitCategoryEntityMappings();
			InitIngredientEntityMappings();
			InitInstructionEntityMappings();
			InitRecipeEntityMappings();
			InitRecipeCategoryEntityMappings();
			InitUserEntityMappings();
			InitVersionInfoEntityMappings();
		}

		/// <summary>Inits CategoryEntity's mappings</summary>
		private void InitCategoryEntityMappings()
		{
			this.AddElementMapping("CategoryEntity", @"recipesapp", @"public", "category", 3, 0);
			this.AddElementFieldMapping("CategoryEntity", "Id", "id", false, "Integer", 0, 10, 0, true, "public.category_id_seq", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("CategoryEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 1);
			this.AddElementFieldMapping("CategoryEntity", "Name", "name", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 2);
		}

		/// <summary>Inits IngredientEntity's mappings</summary>
		private void InitIngredientEntityMappings()
		{
			this.AddElementMapping("IngredientEntity", @"recipesapp", @"public", "ingredient", 4, 0);
			this.AddElementFieldMapping("IngredientEntity", "Id", "id", false, "Integer", 0, 10, 0, true, "public.ingredient_id_seq", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("IngredientEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 1);
			this.AddElementFieldMapping("IngredientEntity", "Name", "name", false, "Varchar", 1000, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("IngredientEntity", "RecipeId", "recipe_id", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 3);
		}

		/// <summary>Inits InstructionEntity's mappings</summary>
		private void InitInstructionEntityMappings()
		{
			this.AddElementMapping("InstructionEntity", @"recipesapp", @"public", "instruction", 4, 0);
			this.AddElementFieldMapping("InstructionEntity", "Id", "id", false, "Integer", 0, 10, 0, true, "public.instruction_id_seq", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("InstructionEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 1);
			this.AddElementFieldMapping("InstructionEntity", "Name", "name", false, "Varchar", 1000, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("InstructionEntity", "RecipeId", "recipe_id", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 3);
		}

		/// <summary>Inits RecipeEntity's mappings</summary>
		private void InitRecipeEntityMappings()
		{
			this.AddElementMapping("RecipeEntity", @"recipesapp", @"public", "recipe", 3, 0);
			this.AddElementFieldMapping("RecipeEntity", "Id", "id", false, "Integer", 0, 10, 0, true, "public.recipe_id_seq", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("RecipeEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 1);
			this.AddElementFieldMapping("RecipeEntity", "Title", "title", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 2);
		}

		/// <summary>Inits RecipeCategoryEntity's mappings</summary>
		private void InitRecipeCategoryEntityMappings()
		{
			this.AddElementMapping("RecipeCategoryEntity", @"recipesapp", @"public", "recipe_category", 4, 0);
			this.AddElementFieldMapping("RecipeCategoryEntity", "CategoryId", "category_id", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("RecipeCategoryEntity", "Id", "id", false, "Integer", 0, 10, 0, true, "public.recipe_category_id_seq", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("RecipeCategoryEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 2);
			this.AddElementFieldMapping("RecipeCategoryEntity", "RecipeId", "recipe_id", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 3);
		}

		/// <summary>Inits UserEntity's mappings</summary>
		private void InitUserEntityMappings()
		{
			this.AddElementMapping("UserEntity", @"recipesapp", @"public", "user", 6, 0);
			this.AddElementFieldMapping("UserEntity", "Id", "id", false, "Integer", 0, 10, 0, true, "public.user_id_seq", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("UserEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 1);
			this.AddElementFieldMapping("UserEntity", "Password", "password", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("UserEntity", "RefreshToken", "refresh_token", true, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("UserEntity", "RefreshTokenExpiry", "refresh_token_expiry", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 4);
			this.AddElementFieldMapping("UserEntity", "Username", "username", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 5);
		}

		/// <summary>Inits VersionInfoEntity's mappings</summary>
		private void InitVersionInfoEntityMappings()
		{
			this.AddElementMapping("VersionInfoEntity", @"recipesapp", @"public", "VersionInfo", 3, 2);
			this.AddElementFieldMapping("VersionInfoEntity", "AppliedOn", "AppliedOn", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 0);
			this.AddElementFieldMapping("VersionInfoEntity", "Description", "Description", true, "Varchar", 1024, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("VersionInfoEntity", "Version", "Version", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 2);
		}

	}
}
